# Generated by Django 4.0.4 on 2022-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('SR', 'SR'), ('VK', 'VK'), ('Krishna', 'Krishna'), ('Gandhi', 'Gandhi'), ('Ram', 'Ram'), ('Budh', 'Budh'), ('Malviya', 'Malviya'), ('Bhagirath', 'Bhagirath'), ('Meera', 'Meera')], max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
