# Generated by Django 4.0.4 on 2022-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_hostel_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('SR', 'SR'), ('VK', 'VK'), ('Krishna', 'Krishna'), ('Gandhi', 'Gandhi'), ('Ram', 'Ram'), ('Budh', 'Budh'), ('Malviya', 'Malviya'), ('Bhagirath', 'Bhagirath'), ('Meera', 'Meera')], default='SR', max_length=25),
        ),
    ]
