# Generated by Django 4.0.4 on 2022-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_branch',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_branch',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
