# Generated by Django 4.0.4 on 2022-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_first_branch_profile_second_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(default='SR', max_length=25),
        ),
    ]
