# Generated by Django 4.0.4 on 2022-06-03 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_s_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='S_Question',
            new_name='SQuestion',
        ),
    ]
